# Generated by Django 4.2.6 on 2023-10-18 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestimonialCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="testimonial_logos/")),
                ("header_title", models.CharField(blank=True, max_length=200, null=True)),
                ("custom_message", models.TextField(blank=True, null=True)),
                ("questions", models.JSONField(blank=True, default=list, null=True)),
                ("extra_info", models.JSONField(blank=True, default=dict, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("responses", models.JSONField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testimonial.testimonialcampaign"
                    ),
                ),
            ],
        ),
    ]
