# Generated by Django 4.2.6 on 2023-10-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(blank=True, max_length=255, null=True)),
                ("required", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("TEXT", "TEXT"), ("CHECKBOX", "CHECKBOX")],
                        default="TEXT",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="testimonialcampaign",
            name="extra_info",
        ),
        migrations.RemoveField(
            model_name="testimonialcampaign",
            name="questions",
        ),
        migrations.AddField(
            model_name="testimonialcampaign",
            name="extra_info",
            field=models.ManyToManyField(blank=True, to="testimonial.extrainfo"),
        ),
        migrations.AddField(
            model_name="testimonialcampaign",
            name="questions",
            field=models.ManyToManyField(blank=True, to="testimonial.question"),
        ),
    ]
