# Generated by Django 4.2.6 on 2023-10-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonial", "0002_extrainfo_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrainfo",
            name="type",
            field=models.CharField(
                choices=[("TEXT", "TEXT"), ("CHECKBOX", "CHECKBOX")], default="TEXT", max_length=20
            ),
        ),
    ]
