# Generated by Django 4.2.6 on 2023-10-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonial", "0003_alter_extrainfo_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Question",
            new_name="CustomQuestion",
        ),
        migrations.RenameField(
            model_name="testimonialcampaign",
            old_name="questions",
            new_name="custom_questions",
        ),
        migrations.AddField(
            model_name="testimonialcampaign",
            name="q1",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Question One"),
        ),
        migrations.AddField(
            model_name="testimonialcampaign",
            name="q2",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Question Two"),
        ),
        migrations.AddField(
            model_name="testimonialcampaign",
            name="q3",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Question Three"),
        ),
    ]
