# Generated by Django 4.2.6 on 2023-10-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonial", "0004_rename_question_customquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customquestion",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="extrainfo",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
