# Generated by Django 4.2.6 on 2023-10-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonial", "0005_customquestion_slug_extrainfo_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
