# Generated by Django 4.2.6 on 2023-10-17 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="profile_image",
            new_name="avatar",
        ),
    ]
