# Generated by Django 4.2.6 on 2023-10-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_profile_image_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/", verbose_name="Profile Image"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="cover_images/", verbose_name="Cover Image"),
        ),
    ]
